
const appConstants = {
    statusCode: {
        UNAUTHORIZED: 400,
        SUCCESS: 200,
        NOTFOUND:404
    },
    alertTypeNames:{
    WALLET_BALANCE:"WALLET_BALANCE",
    GAS_PRICE:"GAS_PRICE",
    INCOMING_ETH:"INCOMING_ETH",
    OUTGOING_ETH:"OUTGOING_ETH",
    CONTRACT_INTERACTION:"CONTRACT_INTERACTION",
    TOKEN_TRANSFER:"TOKEN_TRANSFER",
    LARGE_TRANSACTION:"LARGE_TRANSACTION"
    }
}

export default appConstants